name: Auto approve and Merge Dependabot PRs
on:
  pull_request_target:
    types: [labeled]
permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve:
    name: Auto-approve dependabot PRs
    runs-on: ubuntu-24.04
    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved automated PR"
      - name: Enable auto-merge for Dependabot PRs
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr merge --auto --merge "$PR_URL"
